<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Default test(failed)" time="0.079" errors="0" timestamp="2023-11-14T19:11:02 IST">
  <testcase classname="learnTestNG.TestScenario1" name="first_testcase" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at learnTestNG.TestScenario1.first_testcase(TestScenario1.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
</testsuite> <!-- Default test(failed) -->
